### ISSUE TITLE
Větší menší rules

### ISSUE THREAD

**Issue by jamesek** [HoraJan/bim-viewer#3]
Nevím, jak zadat větší menší rule .. např:

{OverallWidth: {$gt: 1500}} 

Hází 

[Log] TypeError: undefined is not a function (near '...rule.data.forEach...')
(anonymní funkce) — App.js:60
forEach
assignData — App.js:58
promiseReactionJob

**Comment by HoraJan** [comment]
je treba legalni json, tedy {"$gt": 1500}

**Comment by jamesek** [comment]
!!, commit, díky
